export type Article = { slug: string; title: string; description: string; category: string; tags: string[]; publishedAt: string; updatedAt: string; readingMinutes: number; featured: boolean; content: string };
export const articles: Article[] = [
  { slug: 'build-a-calm-digital-garden', title: '搭一座安静、耐用的数字花园', description: '从内容结构、阅读节奏到技术取舍，记录这个博客诞生时最重要的几个决定。', category: '创作札记', tags: ['博客', '设计', '写作'], publishedAt: '2026-08-18', updatedAt: '2026-08-26', readingMinutes: 7, featured: true, content: `## 写在开始之前\n\n个人网站最迷人的地方，不是功能有多少，而是它能否诚实地容纳一个人的变化。\n\n> 好的数字花园不急着长满，它先给想法留出呼吸。\n\n## 内容先于装饰\n\n我把文章、项目和关于页面看成三条线：文章保存思考，项目呈现行动，关于页面提供上下文。首页只负责把它们安静地连接起来。\n\n## 技术选择\n\n这次使用 TypeScript 与可迁移的内容模型。公开内容进入版本控制，敏感信息则永远不会以明文抵达服务器。\n\n\`\`\`ts\ntype Note = {\n  title: string\n  publishedAt: string\n  tags: string[]\n}\n\`\`\`\n\n## 下一步\n\n持续写作比一次性装修更重要。先让路径清楚、文字舒服，再慢慢增加真正需要的能力。` },
  { slug: 'zero-knowledge-vault-notes', title: '零知识保险库：边界比口号重要', description: '客户端加密、会话认证和威胁模型如何各司其职，以及哪些承诺不应该轻易说出口。', category: '安全工程', tags: ['Web Crypto', '安全', '隐私'], publishedAt: '2026-07-09', updatedAt: '2026-07-14', readingMinutes: 9, featured: true, content: `## 两把不同的钥匙\n\n登录密码回答“你是谁”，主密码回答“你能否解开数据”。把两者分开，服务器就不需要知道解密秘密。\n\n## 每条记录独立随机参数\n\nAES-GCM 要求 nonce 不重复。本项目为每次加密生成新的 96 位随机 IV，并用 PBKDF2 派生只存在于内存中的密钥。\n\n## 不能被界面掩盖的限制\n\n浏览器无法保证系统剪贴板一定被清空；XSS 仍可能读取已解锁页面中的数据；忘记主密码时，零知识模型也无法代替你恢复。\n\n## 安全不是单点功能\n\n真正的边界来自加密、授权、CSP、限速、无缓存策略与克制的日志共同作用。` },
  { slug: 'small-tools-long-life', title: '小工具，长寿命', description: '如何控制个人项目的复杂度，让一个周末原型有机会陪你很多年。', category: '工程实践', tags: ['维护', '产品思维', '博客'], publishedAt: '2025-12-21', updatedAt: '2026-01-03', readingMinutes: 5, featured: false, content: `## 从删除功能开始\n\n个人项目最稀缺的资源不是算力，而是未来的注意力。每增加一个依赖、后台任务或外部服务，都在向未来借时间。\n\n## 让数据能带走\n\n优先选择容易导出的格式，保留清晰的数据边界，并为迁移写下最短路径。\n\n## 写给未来的自己\n\nREADME 不必宏大，但要回答：它为什么存在、怎样启动、哪里最危险。` },
];
export type Project = { slug: string; name: string; description: string; category: string; tech: string[]; status: string; website: string; repository?: string; featured: boolean; mark: string };
export const projects: Project[] = [
  { slug: 'luna-focus', name: 'Luna Focus（虚构演示）', description: '把番茄钟与每日复盘放在同一个安静界面里。', category: '效率工具', tech: ['React', 'PWA'], status: '开发中', website: 'https://example.com/luna-focus', repository: 'https://github.com/example/luna-focus', featured: true, mark: '月' },
  { slug: 'hanabi-api', name: 'Hanabi API（虚构演示）', description: '面向独立开发者的轻量通知编排服务。', category: '开发者工具', tech: ['TypeScript', 'Workers'], status: '维护中', website: 'https://example.com/hanabi-api', repository: 'https://github.com/example/hanabi-api', featured: true, mark: '火' },
  { slug: 'mist-gallery', name: 'Mist Gallery（虚构演示）', description: '为插画习作准备的本地优先归档工具。', category: '创作工具', tech: ['Vite', 'IndexedDB'], status: '概念验证', website: 'https://example.com/mist-gallery', featured: false, mark: '雾' },
];
