const encoder=new TextEncoder();
export function toBase64(bytes:Uint8Array){let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
export function fromBase64(value:string){const normalized=value.replace(/-/g,'+').replace(/_/g,'/');const binary=atob(normalized);return Uint8Array.from(binary,char=>char.charCodeAt(0))}
export function randomToken(bytes=32){const value=new Uint8Array(bytes);crypto.getRandomValues(value);return toBase64(value)}
export async function sha256(value:string){return toBase64(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value))))}
export function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let index=0;index<a.length;index++)diff|=a.charCodeAt(index)^b.charCodeAt(index);return diff===0}
export async function derivePasswordHash(password:string,salt:string,iterations=600_000){const material=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:fromBase64(salt),iterations},material,256);return toBase64(new Uint8Array(bits))}
export async function verifyPassword(password:string,encoded:string){const [iterations,salt,expected]=encoded.split('$');if(!iterations||!salt||!expected)return false;const actual=await derivePasswordHash(password,salt,Number(iterations));return safeEqual(actual,expected)}
function decodeBase32(value:string){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';const clean=value.toUpperCase().replace(/[^A-Z2-7]/g,'');let bits='';for(const char of clean){const index=alphabet.indexOf(char);if(index<0)throw new Error('Invalid base32');bits+=index.toString(2).padStart(5,'0')}const bytes=[];for(let index=0;index+8<=bits.length;index+=8)bytes.push(parseInt(bits.slice(index,index+8),2));return new Uint8Array(bytes)}
export async function verifyTotp(secret:string,code:string,now=Date.now()){if(!/^\d{6}$/.test(code))return false;const key=await crypto.subtle.importKey('raw',decodeBase32(secret),{name:'HMAC',hash:'SHA-1'},false,['sign']);for(let drift=-1;drift<=1;drift++){let counter=Math.floor(now/30_000)+drift;const data=new Uint8Array(8);for(let index=7;index>=0;index--){data[index]=counter&255;counter=Math.floor(counter/256)}const signed=new Uint8Array(await crypto.subtle.sign('HMAC',key,data));const offset=signed[signed.length-1]&15;const value=(((signed[offset]&127)<<24)|(signed[offset+1]<<16)|(signed[offset+2]<<8)|signed[offset+3])%1_000_000;if(safeEqual(value.toString().padStart(6,'0'),code))return true}return false}
