'use client';
import { fromBase64, randomToken, toBase64 } from '@/lib/security';
const encoder=new TextEncoder();const decoder=new TextDecoder();
export type EncryptedPayload={ciphertext:string;iv:string};export type VaultProfile={salt:string;verifierIv:string;verifierCiphertext:string;kdfIterations:number};
export async function deriveVaultKey(masterPassword:string,profile:Pick<VaultProfile,'salt'|'kdfIterations'>){const material=await crypto.subtle.importKey('raw',encoder.encode(masterPassword),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt:fromBase64(profile.salt),iterations:profile.kdfIterations},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
export async function encryptJson(key:CryptoKey,value:unknown):Promise<EncryptedPayload>{const iv=new Uint8Array(12);crypto.getRandomValues(iv);const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(value)));return{ciphertext:toBase64(new Uint8Array(encrypted)),iv:toBase64(iv)}}
export async function decryptJson<T>(key:CryptoKey,payload:EncryptedPayload):Promise<T>{const decrypted=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromBase64(payload.iv)},key,fromBase64(payload.ciphertext));return JSON.parse(decoder.decode(decrypted)) as T}
export async function createVaultProfile(masterPassword:string):Promise<{profile:VaultProfile;key:CryptoKey}>{const salt=randomToken(16);const kdfIterations=600_000;const key=await deriveVaultKey(masterPassword,{salt,kdfIterations});const verifier=await encryptJson(key,{marker:'starry-vault-v1'});return{key,profile:{salt,kdfIterations,verifierIv:verifier.iv,verifierCiphertext:verifier.ciphertext}}}
export async function unlockVault(masterPassword:string,profile:VaultProfile){const key=await deriveVaultKey(masterPassword,profile);const value=await decryptJson<{marker:string}>(key,{iv:profile.verifierIv,ciphertext:profile.verifierCiphertext});if(value.marker!=='starry-vault-v1')throw new Error('主密码不正确');return key}
