import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowRight, CalendarDays, Clock3 } from 'lucide-react';
import { ImagePreview } from '@/components/image-preview';
import { Comments } from '@/components/comments';
import { ReadingProgress } from '@/components/reading-progress';
import { ArticleStatsBar } from '@/components/article-stats';
import { CodeCopyEnhancer } from '@/components/code-copy';
import { getArticleBySlug, listPublishedArticles } from '@/lib/site-content';
import { getHeadings, renderMarkdown } from '@/lib/markdown';
import { countWords } from '@/lib/word-count';
export const dynamic = 'force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const article=await getArticleBySlug(slug);if(!article)return{};return{title:article.title,description:article.description,openGraph:{title:article.title,description:article.description,type:'article',publishedTime:article.publishedAt,modifiedTime:article.updatedAt,images:['/images/cover-miku-ocean.jpg']},twitter:{card:'summary_large_image',title:article.title,description:article.description,images:['/images/cover-miku-ocean.jpg']}}}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const articles=await listPublishedArticles();const index=articles.findIndex(item=>item.slug===slug);const article=index>=0?articles[index]:await getArticleBySlug(slug,{includeDrafts:false});if(!article)notFound();const headings=getHeadings(article.content);const related=articles.filter(item=>item.slug!==slug&&item.tags.some(tag=>article.tags.includes(tag))).slice(0,2);return <main className="article-page shell"><ReadingProgress/><Link className="back-link" href="/articles"><ArrowLeft/> 返回文章列表</Link><header className="article-head"><div className="meta"><span>{article.category}</span><span><Clock3/> {article.readingMinutes} 分钟阅读</span><span>{countWords(article.content)} 字</span></div><h1>{article.title}</h1><p>{article.description}</p><div className="publish-info"><span><CalendarDays/> 发布于 {article.publishedAt}</span><span>更新于 {article.updatedAt}</span></div><div className="tags">{article.tags.map(tag=><span key={tag}>#{tag}</span>)}</div></header><ArticleStatsBar slug={article.slug}/><CodeCopyEnhancer key={article.slug}/><ImagePreview src="/images/night-editorial.png" alt="夜樱窗边的写作场景"/><div className="article-layout"><article className="prose" dangerouslySetInnerHTML={{__html:renderMarkdown(article.content)}}/><aside className="toc"><strong>这篇文章</strong><nav>{headings.map(item=><a href={`#${item.id}`} key={item.id}>{item.text}</a>)}</nav></aside></div><nav className="article-nav">{index>0?<Link href={`/articles/${articles[index-1].slug}`}><small>上一篇</small><span><ArrowLeft/>{articles[index-1].title}</span></Link>:<span/>}{index>=0&&index<articles.length-1?<Link href={`/articles/${articles[index+1].slug}`}><small>下一篇</small><span>{articles[index+1].title}<ArrowRight/></span></Link>:<span/>}</nav>{related.length>0&&<section className="related"><span className="kicker">KEEP READING</span><h2>相关文章</h2><div>{related.map(item=><Link href={`/articles/${item.slug}`} key={item.slug}><strong>{item.title}</strong><span>{item.description}</span></Link>)}</div></section>}<Comments slug={article.slug}/></main>}
